# This is a basic workflow to help you get started with Actions

name: Blob storage website CI

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
    name:
      description: "Person to greet"
      required: true
      default: "bossm0n5t3r"
    home:
      description: "location"
      required: false
      default: "The Octoverse"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_STORAGE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name 'staticwebappmrtest' --overwrite=true --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "CDNTest" --name "staticwebappmrtest" --resource-group "CDN-Workbook-Test-RG"
           
# Azure logout
    - name: logout
      run: |
            az logout
      if: always()
